// @ts-nocheck
// eslint-disable
// biome-ignore lint/*: auto-generated file

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Stage the whole draft into the release directory in CANONICAL layout
 * (Model/Supported|Unsupported[/Variant], sidecar per leaf — see
 * file/stage.rs), then record every leaf in release.json in one write.
 * One command for the whole batch on purpose: members sharing a canonical
 * leaf must merge (poses become file-level metadata), and the old
 * per-model command raced its own release.json read-modify-write.
 */
async addModels(models: StlModel[], releaseDir: string) : Promise<Result<([StlModel, string])[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_models", { models, releaseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRelease(release: Release, imagePaths: string[], otherFilePaths: string[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_release", { release, imagePaths, otherFilePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async finalizeRelease(releaseDir: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_release", { releaseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelCompression(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_compression", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open files with their OS-default application — the "print" hand-off to
 * whatever slicer owns the extension. NOT the opener plugin: its open_path
 * is fire-and-forget (open::that_detached), which reports success even
 * when the OS has no app for the file type, leaving the user with a button
 * that silently does nothing. Launching the OS opener ourselves captures
 * that failure so the UI can react (fall back to revealing the folder).
 */
async openWithDefaultApp(paths: string[]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_with_default_app", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a packed release into the library: verify component checksums,
 * extract (rematerializing dedup-elided names), land it under the same
 * naming scheme create_release uses. A catalog scan afterwards restores
 * the packed curation. `components` limits the run to the named components
 * (selective import / update); None imports everything.
 */
async importRelease(packagePath: string, libraryDir: string, components: string[] | null) : Promise<Result<ImportOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_release", { packagePath, libraryDir, components }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Diff a `release.3pk` against the library without touching anything: per
 * component, is it new, changed, unchanged, packed at rest, or missing its
 * archive? Feeds the selective-import dialog shown before an import runs.
 */
async inspectReleasePackage(packagePath: string, libraryDir: string) : Promise<Result<PackageInspection, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_release_package", { packagePath, libraryDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * WIP releases that never got packed — a successful finalize removes the
 * scratch folder (compression_jobs::perform_compression), so any directory
 * still holding a release.json here is by definition unfinished.
 */
async listReleaseDrafts() : Promise<Result<ReleaseDraftSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_release_drafts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rehydrate a WIP release for the builder UI: release.json only carries
 * {id, path} per model (ModelReference), so the rich curation the UI needs
 * (designer/pose/variant/tags/file_poses…) is read back from each model's
 * own model.json sidecar — the same file add_models staged it to.
 */
async loadReleaseDraft(releaseDir: string) : Promise<Result<[Release, StlModel[]], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_release_draft", { releaseDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectBlender() : Promise<Result<BlenderInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_blender") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detection plus the version verdict, in one call the first-run dialog,
 * Settings, and the Render view all share.
 */
async checkBlender() : Promise<Result<BlenderCheck, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_blender") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kick off the managed download; progress arrives as
 * BlenderProvisionStatus events carrying the returned job_id.
 */
async downloadBlender() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_blender") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelBlenderDownload(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_blender_download", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRender(parts: string[], options: RenderOptions) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_render", { parts, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRender(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_render", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read an image as a data URL for the branding bake. The webview draws
 * the finished render (plus logo) onto a canvas — but images loaded via
 * the asset: protocol are cross-origin and TAINT the canvas, making
 * toBlob() throw. Data URLs don't, so the bytes take this detour.
 */
async readImageBase64(path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_image_base64", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Overwrite an existing render with the branding-composited PNG the
 * webview produced. Three guards keep a bad bake from eating a good
 * render: the target must already exist (this only ever re-writes a
 * finished render), the bytes must carry the PNG magic (a blank/failed
 * canvas export dies here, not on disk), and the write goes through
 * temp + rename so a crash can't leave a half-written file.
 */
async writePngBase64(path: string, data: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_png_base64", { path, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a shareable look file for import. The webview's fs capability is
 * read-only and dialog-driven anyway; this narrow command keeps the same
 * posture: .json only, 1 MB cap (a look file is ~1 KB — anything bigger is
 * a mis-pick), parsing/validation stays client-side where the schema lives.
 */
async readLookJson(path: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_look_json", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write a shareable look file where the save dialog pointed. Mirrors
 * write_png_base64's guarded style: the contents must parse as JSON (the
 * caller builds them, but a corrupt write would burn the person it was
 * shared WITH), and temp + rename means no half-written file survives.
 */
async writeLookJson(path: string, contents: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_look_json", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPending3dpak() : Promise<string | null> {
    return await TAURI_INVOKE("get_pending_3dpak");
},
async startCatalogScan(root: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_catalog_scan", { root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The configured catalog folders with their indexed footprint. Folders the
 * user added but never scanned report zero counts and no last_scan.
 */
async listCatalogRoots() : Promise<Result<CatalogRootSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_catalog_roots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a catalog folder without scanning it yet. Returns the updated
 * list. Adding is idempotent; a folder nested in (or swallowing) a
 * configured one is rejected — overlapping roots would double-index.
 */
async addCatalogRoot(path: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_catalog_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop a catalog folder and purge its slice of the index. The disk is
 * never touched; user tags/metadata for the purged models go with them
 * (their durable home is the model.json sidecars), so re-adding the
 * folder later just means a rescan.
 */
async removeCatalogRoot(path: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_catalog_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Choose (or clear, with None) the staging folder Clean up drains the
 * other folders into. Must already be a configured catalog folder.
 */
async setPrimaryCatalogRoot(path: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_primary_catalog_root", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDuplicateScan() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_duplicate_scan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelCatalogJob(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_catalog_job", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchCatalog(query: string, tags: string[], limit: number, offset: number) : Promise<Result<CatalogSearchResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_catalog", { query, tags, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogTags() : Promise<Result<TagCount[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addCatalogTag(dirPath: string, tag: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_catalog_tag", { dirPath, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeCatalogTag(dirPath: string, tag: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_catalog_tag", { dirPath, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tag/untag every member of a group at once — a tag describes the mini,
 * not one support build of it.
 */
async addGroupTag(groupName: string, tag: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_group_tag", { groupName, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGroupTag(groupName: string, tag: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_group_tag", { groupName, tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogModelFiles(dirPath: string, variantKey: string | null) : Promise<Result<CatalogFile[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_model_files", { dirPath, variantKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogStats() : Promise<Result<CatalogStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDuplicateGroups() : Promise<Result<DuplicateGroup[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_duplicate_groups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogReleases() : Promise<Result<ReleaseSummary[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_releases") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogDesigners() : Promise<Result<DesignerCount[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_designers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update one member's metadata, then propagate the shared facets (variant,
 * pose, scale) to its support twins — the supported/unsupported builds of
 * the same sculpt, matched by exact path structure. Returns how many twins
 * received the edit so the UI can say so. Only Some values propagate;
 * clears stay local to the edited member.
 */
async updateModelMetadata(dirPath: string, meta: ModelMetaUpdate) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_model_metadata", { dirPath, meta }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy an image into the app's previews dir and point the model at it.
 * The copy (not a reference) is deliberate: render outputs and picked
 * images live wherever the user left them and may be cleaned up; the
 * catalog preview must not die with them. The filename is a stable
 * per-model hash plus a timestamp — a fresh URL each time, because the
 * webview caches aggressively by URL, with older copies swept first.
 */
async setModelPreview(dirPath: string, imagePath: string, variantKey: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_preview", { dirPath, imagePath, variantKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDuplicateFiles(filePaths: string[]) : Promise<Result<BatchOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_duplicate_files", { filePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge a duplicate group: every path in `duplicate_paths` becomes another
 * name for `keep_path`'s bytes (a hardlink), freeing the copies while every
 * variant keeps a working file. The catalog's identities are updated in
 * place so the group reports "shared" without waiting for a rescan.
 */
async mergeDuplicateFiles(keepPath: string, duplicatePaths: string[]) : Promise<Result<BatchOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_duplicate_files", { keepPath, duplicatePaths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probe whether the volume holding `path` supports hardlink merging.
 * Consulted by the duplicates panel so link-less filesystems (exFAT, some
 * NAS mounts) get delete-only instead of a button that can't work.
 */
async supportsFileLinks(path: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("supports_file_links", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchMoveModels(operations: MoveOperation[]) : Promise<Result<BatchOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_move_models", { operations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dry-run the normalizer: what would move where to make the disk match
 * the curated catalog. Read-only — nothing happens until apply.
 */
async planNormalize(designer: string | null, group: string | null) : Promise<Result<NormalizePlan, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_normalize", { designer, group }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute approved normalizer moves. The frontend sends these in chunks
 * so a big NAS batch shows progress and stays cancellable between calls.
 */
async applyNormalize(ops: NormalizeOp[]) : Promise<Result<BatchOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_normalize", { ops }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * After the moves: write authoritative model.json sidecars, sweep emptied
 * dirs, rebuild search. Returns human-readable warnings.
 */
async finalizeNormalize(groupNames: string[], oldDirs: string[]) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("finalize_normalize", { groupNames, oldDirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchCatalogGroups(query: string, tags: string[], designer: string | null, sort: string | null, limit: number, offset: number) : Promise<Result<CatalogGroupResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_catalog_groups", { query, tags, designer, sort, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCatalogGroupMembers(groupName: string) : Promise<Result<CatalogEntry[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_group_members", { groupName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The scanner-level groups shown under one card. Length > 1 means the card
 * was combined (or renamed into a collision) and can be split — the UI
 * offers "split" exactly then, and rename-to-empty performs it.
 */
async getCatalogGroupSources(groupName: string) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_catalog_group_sources", { groupName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Where a rename/combine of `group_name` would actually reach — call this
 * before committing one, so the UI can warn when a generic scanner-derived
 * name ("Spear") turns out to also belong to an unrelated designer/release
 * (see the group_renames CREATE TABLE comment: no root/designer scoping).
 */
async getGroupRenameOrigins(groupName: string) : Promise<Result<GroupOrigin[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_group_rename_origins", { groupName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove one mis-combined source from a card (its rename row) so it comes
 * back as its own card — the surgical undo, next to full split.
 */
async detachCatalogGroupSource(groupName: string, sourceGroup: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detach_catalog_group_source", { groupName, sourceGroup }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pick which member's image fronts the group's card.
 */
async setGroupCover(groupName: string, dirPath: string, variantKey: string | null) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_group_cover", { groupName, dirPath, variantKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameCatalogGroup(groupName: string, newName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_catalog_group", { groupName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async combineCatalogGroups(groupNames: string[], targetName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("combine_catalog_groups", { groupNames, targetName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assign files to a pose (with optional per-file support) so a dump
 * folder can be split into pose members. Metadata only — nothing moves on
 * disk. Returns the number of known files assigned.
 */
async assignFilesToPose(paths: string[], variant: string | null, pose: string | null, supportStatus: string | null) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_files_to_pose", { paths, variant, pose, supportStatus }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Revert files to plain members of their folder. Returns how many
 * assignments existed — 0 tells the UI the selection was never filed.
 */
async clearFilePose(paths: string[]) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_file_pose", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The pose assignments under a folder, for the split UI.
 */
async getFileVariants(dirPath: string) : Promise<Result<FileVariant[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_variants", { dirPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compress each model dir into a model.plinthpack (compressed at rest),
 * sequentially — per-model atomicity keeps the crash surface to one model,
 * and a cancelled or crashed batch resumes by re-running the same selection
 * (already-packed models just finish their bookkeeping and count as done).
 * Cancel via cancel_catalog_job; progress via PackStatus events.
 */
async packModels(modelDirs: string[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pack_models", { modelDirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore packed models to loose files (archive + sidecar removed), the
 * mirror of pack_models: sequential, cancellable between models, index
 * updated per model so no rescan is needed.
 */
async unpackModels(modelDirs: string[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unpack_models", { modelDirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Which model folders a bulk pack would touch: everything with loose model
 * files under the given designer facet and/or checked group names. The
 * frontend shows the count in the confirm dialog, then feeds the same list
 * to pack_models — one resumable job for a whole designer.
 */
async getPackCandidates(designer: string | null, groups: string[]) : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pack_candidates", { designer, groups }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Make `paths` readable on disk, extracting packed ones from their
 * archives as EPHEMERAL working copies — the archive stays authoritative
 * and cleanup_ephemeral_files takes the copies back. Awaits completion:
 * the promise resolving means the bytes are there, so callers just chain
 * their print/preview/render after it. Progress rides the PackStatus
 * stream (phase "extract"); the Started event carries the job_id the
 * frontend can feed to cancel_catalog_job.
 */
async ensureModelFiles(paths: string[]) : Promise<Result<EnsureOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_model_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Take back the working copies ensure_model_files materialized — the
 * requested paths, or every live extract when the list is empty (the
 * app-exit sweep). Files that changed since extraction are reported and
 * kept: they're the user's data now (saved supports, edits).
 */
async cleanupEphemeralFiles(paths: string[]) : Promise<Result<BatchOutcome, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_ephemeral_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startBatchRender(targets: BatchRenderTarget[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_batch_render", { targets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything the batch confirm dialog needs, resolved through
 * group_members (NOT raw SQL: expand_file_variants is what gives fanned
 * members their own variant_key + per-variant preview state).
 */
async getRenderCandidates(designer: string | null, groups: string[]) : Promise<Result<RenderCandidate[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_render_candidates", { designer, groups }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the orientation a render used ("the render IS the chosen
 * orientation") — the studio calls this after a successful catalog-preview
 * render, and batch renders read it back so re-renders never need
 * repositioning.
 */
async setModelRotation(dirPath: string, rotation: [number, number, number]) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_rotation", { dirPath, rotation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Find minihoard and prove it runs (`--version`). None simply means the
 * egg stays hidden.
 */
async detectMinihoard() : Promise<MinihoardInfo | null> {
    return await TAURI_INVOKE("detect_minihoard");
},
/**
 * Launch one whitelisted minihoard run and stream its output as events.
 * Returns the job id immediately; MinihoardStatus::Finished closes it.
 */
async runMinihoard(binaryPath: string, args: string[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_minihoard", { binaryPath, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill the active run (the "stop" button). Emits Finished(success=false).
 */
async cancelMinihoard(jobId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_minihoard", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
batchRenderStatus: BatchRenderStatus,
blenderProvisionStatus: BlenderProvisionStatus,
compressionStatus: CompressionStatus,
duplicateStatus: DuplicateStatus,
minihoardStatus: MinihoardStatus,
packStatus: PackStatus,
renderStatus: RenderStatus,
scanStatus: ScanStatus
}>({
batchRenderStatus: "batch-render-status",
blenderProvisionStatus: "blender-provision-status",
compressionStatus: "compression-status",
duplicateStatus: "duplicate-status",
minihoardStatus: "minihoard-status",
packStatus: "pack-status",
renderStatus: "render-status",
scanStatus: "scan-status"
})

/** user-defined constants **/



/** user-defined types **/

export type AppError = { InvalidInput: string } | { IoError: string } | { JsonError: string } | { FileProcessingError: string } | { ConfigError: string } | { NotFoundError: string } | { ImageProcessingError: string } | { UserCancelled: string }
/**
 * Outcome of a batch that may partially succeed — the counts and the
 * per-item errors travel together so the UI can report both.
 */
export type BatchOutcome = { succeeded: number; errors: string[] }
export type BatchRenderCancelledStatus = { job_id: string; succeeded: number }
export type BatchRenderCompletedStatus = { job_id: string; succeeded: number; failed: number; total_models: number; elapsed_seconds: number }
export type BatchRenderFailedStatus = { job_id: string; error: string; 
/**
 * Models finished before the failure — their previews are already
 * persisted and real.
 */
succeeded: number }
export type BatchRenderModelStatus = { job_id: string; model_index: number; dir_path: string; variant_key: string | null; ok: boolean; error: string | null }
export type BatchRenderProgressStatus = { job_id: string; 
/**
 * Display name of the model currently rendering.
 */
current_model: string; 
/**
 * 1-based position in the batch.
 */
model_index: number; total_models: number; 
/**
 * Cycles sample progress of the current model.
 */
model_percent: number; 
/**
 * Whole-batch percent: (finished*100 + model_percent) / total.
 */
percent: number }
export type BatchRenderStartedStatus = { job_id: string; total_models: number }
/**
 * Batch preview rendering: many models, ONE Blender launch. Deliberately
 * its own stream — RenderStatus is the studio's single-job protocol and
 * batch events flowing through it would hijack that UI.
 */
export type BatchRenderStatus = { Started: BatchRenderStartedStatus } | { Progress: BatchRenderProgressStatus } | 
/**
 * One model finished (ok or not) — previews land incrementally, so the
 * catalog can refresh without waiting for the whole sweep.
 */
{ ModelFinished: BatchRenderModelStatus } | { Completed: BatchRenderCompletedStatus } | { Failed: BatchRenderFailedStatus } | { Cancelled: BatchRenderCancelledStatus }
/**
 * One model of the batch, as the frontend selected it (a RenderCandidate
 * the user confirmed). rotation is the stored "x,y,z" or null → 90,0,0.
 */
export type BatchRenderTarget = { dir_path: string; variant_key: string | null; name: string; parts: string[]; rotation: string | null }
export type BlenderCheck = { verdict: BlenderVerdict; 
/**
 * None only when Missing
 */
info: BlenderInfo | null; 
/**
 * The pinned version the download pipeline would install — dialog copy
 * and the first-run acknowledgement key
 */
managed_version: string; 
/**
 * Whether the detected binary is one we downloaded ourselves
 */
is_managed: boolean }
export type BlenderInfo = { path: string; version: string }
export type BlenderProvisionStatus = { Started: ProvisionStartedStatus } | { Progress: ProvisionProgressStatus } | 
/**
 * Post-download work; Progress stops once the bytes are all here.
 */
{ Extracting: ProvisionExtractingStatus } | { Completed: ProvisionCompletedStatus } | { Failed: ProvisionFailedStatus } | { Cancelled: ProvisionCancelledStatus }
/**
 * How a detected Blender measures against the render gate
 * (provision::MIN_VERSION / RECOMMENDED_VERSION). Only Missing and TooOld
 * disable rendering; Outdated is a suggestion the user may dismiss.
 */
export type BlenderVerdict = "Missing" | "TooOld" | "Outdated" | "Ok"
export type CancelledStatus = { job_id: string }
export type CatalogEntry = { dir_path: string; 
/**
 * Effective display name: the user's custom_name when set, else the
 * scanner's. custom_name below carries the raw override so the UI can
 * distinguish "renamed" from "inferred" (and clear it to revert).
 */
name: string; description: string | null; designer: string | null; release_name: string | null; preview_path: string | null; tags: string[]; file_count: number; total_size_bytes: number; 
/**
 * The facet between support and pose — a weapon/sculpt option
 * (sword, mounted, …). Free-text, user-supplied (no scanner inference).
 */
variant: string | null; pose: string | null; scale: string | null; support_status: string | null; release_date: string | null; custom_name: string | null; 
/**
 * The studio/brand. Scanned from the release for release models, and
 * user-overridable per model. sculptor (the individual artist) has no
 * folder signal, so it comes only from the user or an imported manifest.
 */
sculptor: string | null; 
/**
 * Base sizes in mm: "25", or "60x35" for ovals/rectangles.
 */
base_round_mm: string | null; base_square_mm: string | null; 
/**
 * Set only on members synthesized from file→pose assignments: a stable
 * `{dir_path}\u{1f}{pose}` handle ("...\u{1f}" for the residual
 * unassigned member). None means a whole-folder member — its dir_path
 * alone identifies it. The UI keys members on `variant_key ?? dir_path`
 * and passes it back to fetch only that pose's files.
 */
variant_key: string | null; 
/**
 * The scanner-level group this member belongs to — the unit a combine
 * maps and a detach removes. Differs from the card's group_name when
 * the member is only in the card via a rename/combine.
 */
source_group: string; 
/**
 * True when every model file in this member's folder lives inside a
 * pack archive (compressed at rest) — byte-needing actions must unpack
 * or extract first.
 */
packed?: boolean; 
/**
 * Chosen render orientation "x,y,z" (Blender euler degrees) — saved
 * when the studio renders this model; batch re-renders reuse it.
 */
rotation?: string | null; 
/**
 * Measured printed size "60.2x35.1x88.7" in mm, and how many part
 * files make up the model — captured by the render pipeline.
 */
dims_mm?: string | null; part_count?: string | null }
export type CatalogFile = { path: string; file_name: string; extension: string; size_bytes: number; 
/**
 * True when the bytes live inside the model's pack archive — `path` is
 * then where the file lands when extracted, not a file on disk.
 */
packed?: boolean }
/**
 * One logical model: every variant dir (supported/unsupported builds,
 * poses) sharing a group_name, aggregated for the card view. Drill in
 * with get_catalog_group_members.
 */
export type CatalogGroup = { group_name: string; designer: string | null; 
/**
 * Aggregated like designer: any variant's value stands in for the
 * group, so grouping by release works even when only the release
 * models (not later additions) carry the metadata.
 */
release_name: string | null; release_date: string | null; variant_count: number; pose_count: number; support_statuses: string[]; file_count: number; total_size_bytes: number; preview_path: string | null; 
/**
 * True when every member of the group is compressed at rest.
 */
packed?: boolean }
export type CatalogGroupResult = { groups: CatalogGroup[]; total: number }
/**
 * One configured catalog folder and its indexed footprint — a row in the
 * roots management UI. Zero counts with no last_scan mean "added but never
 * scanned"; a stale last_scan is the cue to offer a rescan.
 */
export type CatalogRootSummary = { root: string; model_count: number; file_count: number; total_size_bytes: number; last_scan_epoch: number | null; 
/**
 * The optional staging folder: Clean up drains the other folders'
 * models into this one. At most one row carries it.
 */
primary: boolean }
export type CatalogSearchResult = { entries: CatalogEntry[]; total: number }
export type CatalogStats = { total_models: number; total_files: number; total_size_bytes: number; extensions: ExtensionStat[]; last_scan_epoch: number | null; 
/**
 * Compressed-at-rest accounting: how many models are packed, what their
 * files would occupy loose, and what the archives actually take.
 * total_size_bytes reports logical sizes, so the UI derives real disk
 * usage as total − packed_logical + packed_archive.
 */
packed_models?: number; packed_logical_bytes?: number; packed_archive_bytes?: number }
export type CompletedStatus = { job_id: string; total_files: number; total_size_kb: number; elapsed_seconds: number; folder_path: string }
/**
 * How one incoming component compares to what the library already holds.
 */
export type ComponentState = 
/**
 * Not in the local release (or the release isn't imported yet).
 */
"new" | 
/**
 * Local manifest lists a different archive checksum — an update.
 */
"changed" | 
/**
 * Same checksum both sides; nothing to do.
 */
"unchanged" | 
/**
 * The local copy is packed at rest — unpack before updating.
 */
"packed" | 
/**
 * The component archive isn't next to the .3pk; can't import.
 */
"missing_archive"
export type ComponentStatus = { name: string; state: ComponentState; 
/**
 * f64 (not the manifest's u64): specta refuses integer types TypeScript
 * numbers can't hold, same convention as the catalog's size fields.
 */
size_bytes: number; file_count: number; 
/**
 * Display names of the models inside (custom name when set).
 */
model_names: string[]; 
/**
 * Why the component can't be imported, for Packed/MissingArchive.
 */
detail: string | null }
export type CompressionStatus = { Started: StartedStatus } | { Progress: ProgressStatus } | { Completed: CompletedStatus } | { Failed: FailedStatus } | { Cancelled: CancelledStatus }
export type CompressionType = "SevenZip" | "Zip"
/**
 * One designer and how many logical models (groups) carry that name —
 * feeds the catalog's designer filter dropdown.
 */
export type DesignerCount = { designer: string; model_count: number }
export type DuplicateCancelledStatus = { job_id: string }
export type DuplicateCompletedStatus = { job_id: string; group_count: number; wasted_bytes: number }
export type DuplicateFailedStatus = { job_id: string; error: string }
export type DuplicateGroup = { hash: string; size_bytes: number; paths: string[]; 
/**
 * How many physical copies the paths actually occupy on disk. Hardlinked
 * paths count once, so a fully merged group reports 1 ("shared", nothing
 * to reclaim) and reclaimable space is size_bytes × (distinct_copies − 1).
 */
distinct_copies: number; 
/**
 * The subset of `paths` whose bytes live inside a pack archive — they
 * join detection via their stored checksums but can't be merged or
 * deleted until the model is unpacked; the UI greys them with a hint.
 */
packed_paths?: string[] }
export type DuplicateProgressStatus = { job_id: string; processed: number; total: number }
export type DuplicateStartedStatus = { job_id: string }
export type DuplicateStatus = { Started: DuplicateStartedStatus } | { Progress: DuplicateProgressStatus } | { Completed: DuplicateCompletedStatus } | { Failed: DuplicateFailedStatus } | { Cancelled: DuplicateCancelledStatus }
/**
 * What ensure_model_files did: the paths it materialized from archives
 * (ephemeral working copies, candidates for cleanup_ephemeral_files) vs
 * how many of the requested paths were already loose on disk.
 */
export type EnsureOutcome = { extracted: string[]; already_loose: number }
export type ExtensionStat = { extension: string; file_count: number; total_size_bytes: number }
export type FailedStatus = { job_id: string; error: string }
export type FilePose = { name: string; variant?: string | null; pose?: string | null; support_status?: string | null }
/**
 * A user's per-file pose assignment for a "dump everything in one folder"
 * model. Purely metadata (keyed by path, rescan-safe): the file stays put
 * on disk, but the catalog fans the folder out into one member per pose.
 */
export type FileVariant = { path: string; dir_path: string; variant: string | null; pose: string | null; support_status: string | null }
/**
 * One (designer, release_name) origin among the models a group rename would
 * touch. group_renames is keyed purely on the scanner-derived group name —
 * no root/designer scoping — so a generic name ("Spear") reused by an
 * unrelated designer collides with it silently. More than one distinct
 * origin here means the rename reaches further than whatever single card
 * the user is looking at.
 */
export type GroupOrigin = { designer: string | null; release_name: string | null; model_count: number }
export type ImportOutcome = { release_name: string; designer: string; 
/**
 * The directory the release landed in.
 */
dest_dir: string; 
/**
 * True when the release already existed and this run updated it.
 */
updated: boolean; components: number; files: number; 
/**
 * Per-component problems (checksum mismatch, missing archive, packed at
 * rest); the rest of the release still imports.
 */
errors: string[]; 
/**
 * Non-fatal notes, e.g. locally edited files kept aside as "(edited)".
 */
warnings: string[] }
export type MinihoardFinished = { job_id: string; success: boolean; 
/**
 * Present when the process couldn't run at all (spawn failure).
 */
error: string | null }
export type MinihoardInfo = { path: string; version: string }
export type MinihoardLine = { job_id: string; line: string; 
/**
 * stderr lines render dimmer — minihoard uses stderr for progress
 * chatter, stdout for the actual answers.
 */
is_err: boolean }
export type MinihoardStatus = { Line: MinihoardLine } | { Finished: MinihoardFinished }
export type ModelLocation = { Local: string } | { External: string }
/**
 * The user-editable metadata for one model, saved together from the drawer.
 * A struct rather than positional args because specta caps command arity.
 */
export type ModelMetaUpdate = { custom_name: string | null; variant: string | null; pose: string | null; scale: string | null; support_status: string | null; release_date: string | null; designer: string | null; sculptor: string | null; release_name: string | null; base_round_mm?: string | null; base_square_mm?: string | null }
export type ModelReference = { id: string; location: ModelLocation }
/**
 * One requested directory move: rename `from` to `to` on disk and repoint
 * the catalog index to match.
 */
export type MoveOperation = { from: string; to: string }
/**
 * Everything the normalizer wants to do to ONE model group — shown to the
 * user as a reviewable diff before anything moves.
 */
export type NormalizeGroupPlan = { group_name: string; designer: string; target_dir: string; ops: NormalizeOp[]; 
/**
 * Source dirs to sweep (if emptied) after the moves.
 */
old_dirs: string[]; 
/**
 * Human-readable caveats (name clashes, folders left in place).
 */
notes: string[]; clean: boolean }
/**
 * One planned normalizer action. `kind`: "dir" renames a whole folder
 * (hardlink-safe), "file" moves/renames one file, "pose" only records
 * file-level pose metadata (no filesystem side). `pose` rides along on
 * file ops when a pose-dir merge bakes the pose into the file name.
 */
export type NormalizeOp = { from: string; to: string; kind: string; pose: string | null }
export type NormalizePlan = { 
/**
 * Groups with work to do (already-clean groups are only counted).
 */
groups: NormalizeGroupPlan[]; skipped: NormalizeSkip[]; total_ops: number; clean_groups: number; 
/**
 * Names of the already-clean groups — finalize can be re-run on these
 * to refresh their model.json sidecars without moving anything (the
 * repair path when sidecar-writing logic improves after a cleanup).
 */
clean_names: string[] }
export type NormalizeSkip = { group_name: string; reason: string }
export type PackCancelledStatus = { job_id: string; succeeded: number }
export type PackCompletedStatus = { job_id: string; action: string; succeeded: number; total_models: number; 
/**
 * Loose files left in place because they changed since compression —
 * surfaced so nothing silently stays behind.
 */
kept_files: string[]; elapsed_seconds: number }
export type PackFailedStatus = { job_id: string; error: string; 
/**
 * Models finished before the failure — their state change is real and
 * re-running the batch resumes after them.
 */
succeeded: number }
export type PackProgressStatus = { job_id: string; 
/**
 * "compress" | "verify" | "extract" — what the current model is doing.
 */
phase: string; current_model: string; 
/**
 * 1-based position of the current model in the batch.
 */
model_index: number; total_models: number; processed_size_kb: number; total_size_kb: number; percent: number }
export type PackStartedStatus = { job_id: string; 
/**
 * "pack" or "unpack" — one event stream serves both directions.
 */
action: string; total_models: number }
export type PackStatus = { Started: PackStartedStatus } | { Progress: PackProgressStatus } | { Completed: PackCompletedStatus } | { Failed: PackFailedStatus } | { Cancelled: PackCancelledStatus }
/**
 * What opening a `release.3pk` would do — feeds the selective-import dialog
 * before anything touches the disk.
 */
export type PackageInspection = { release_name: string; designer: string; date: string; version: string; dest_dir: string; 
/**
 * The release dir already holds a manifest — importing means updating.
 */
is_update: boolean; 
/**
 * Set when the destination exists but wasn't written by an import (no
 * readable manifest.json) — importing is refused rather than guessed at.
 */
blocked: string | null; components: ComponentStatus[] }
export type ProgressStatus = { job_id: string; processed_files: number; total_files: number; processed_size_kb: number; total_size_kb: number; percent_size: number; percent_files: number; current_file: string }
export type ProvisionCancelledStatus = { job_id: string }
export type ProvisionCompletedStatus = { job_id: string; info: BlenderInfo }
export type ProvisionExtractingStatus = { job_id: string; 
/**
 * "verify" | "extract" | "install" — mirrors PackProgressStatus.phase.
 */
phase: string }
export type ProvisionFailedStatus = { job_id: string; error: string }
export type ProvisionProgressStatus = { job_id: string; 
/**
 * f64 like wasted_bytes above — u32 caps at 4 GB.
 */
downloaded_bytes: number; total_bytes: number; percent: number }
export type ProvisionStartedStatus = { job_id: string; 
/**
 * The pinned Blender being installed, e.g. "5.1.2".
 */
version: string }
export type Release = { name: string; designer: string; description: string; date: string; version: string; model_references: ModelReference[]; groups: string[]; release_dir: string; images: string[]; other_files: string[] }
/**
 * A WIP release sitting in the scratch dir, not yet packed — surfaced so
 * the builder can resume it without depending on the localStorage draft
 * snapshot surviving. Successful finalize deletes the scratch folder, so
 * anything found here is by definition unfinished.
 */
export type ReleaseDraftSummary = { release_dir: string; name: string; designer: string; model_count: number }
/**
 * One distinct release_name found across scanned models — a read-only
 * aggregation over already-indexed data, NOT a persisted publish log (the
 * catalog doesn't track a "finalized" event, so this just reflects what
 * scanning found on disk).
 */
export type ReleaseSummary = { release_name: string; designer: string | null; model_count: number; total_size_bytes: number }
export type RenderCancelledStatus = { job_id: string }
/**
 * One member the batch renderer could target. `parts` are the member's
 * loose .stl paths; packed members surface with `packed: true` and no
 * extraction (batch is a throughput feature for loose libraries — packed
 * models render fine individually via the drawer).
 */
export type RenderCandidate = { dir_path: string; variant_key: string | null; name: string; parts: string[]; 
/**
 * Stored orientation "x,y,z", if the studio ever saved one.
 */
rotation: string | null; has_preview: boolean; packed: boolean }
export type RenderCompletedStatus = { job_id: string; output_path: string; elapsed_seconds: number }
export type RenderFailedStatus = { job_id: string; error: string }
export type RenderOptions = { 
/**
 * Euler XYZ rotation in degrees, matching render_mini.py --rotate
 */
rotate: [number, number, number]; 
/**
 * Linear RGB resin base color, matching --color (None = locked look default)
 */
color: [number, number, number] | null; azimuth: number | null; elevation: number | null; zoom: number | null; resolution: number | null; samples: number | null; 
/**
 * Tonal look: "rich" (promo contrast) or "flat" (even lighting)
 */
look: string | null; 
/**
 * Output PNG path (None = next to the first STL part)
 */
output_path: string | null; 
/**
 * Allow replacing an existing file; when false an existing output gets
 * a unique -N suffix instead of being clobbered
 */
overwrite?: boolean; 
/**
 * Re-seat parts exported around different origins by stacking them on
 * the part named *base* (render_mini.py --align-parts)
 */
align_parts?: boolean; 
/**
 * JSON overrides for the script's LOOK recipe, passed verbatim as
 * --config. Knob paths and defaults mirror src/utils/renderLookSchema.ts
 */
look_config?: string | null; 
/**
 * Render the configured scale-reference figure beside the model
 * (settings supply the STL path + height; silently off when unset).
 */
scale_reference?: boolean }
export type RenderProgressStatus = { job_id: string; current_sample: number; total_samples: number; percent: number }
export type RenderStartedStatus = { job_id: string; output_path: string }
export type RenderStatus = { Started: RenderStartedStatus } | { Progress: RenderProgressStatus } | { Completed: RenderCompletedStatus } | { Failed: RenderFailedStatus } | { Cancelled: RenderCancelledStatus }
export type ScanCancelledStatus = { job_id: string }
export type ScanCompletedStatus = { job_id: string; total_files: number; total_models: number; elapsed_seconds: number }
export type ScanFailedStatus = { job_id: string; error: string }
export type ScanProgressStatus = { job_id: string; files_indexed: number; current_dir: string }
export type ScanStartedStatus = { job_id: string; root: string }
export type ScanStatus = { Started: ScanStartedStatus } | { Progress: ScanProgressStatus } | { Completed: ScanCompletedStatus } | { Failed: ScanFailedStatus } | { Cancelled: ScanCancelledStatus }
export type Settings = { scratch_dir: string | null; target_dir: string | null; compression_type: CompressionType | null; chunk_size: number | null; max_compression_threads: number | null; blender_path: string | null; 
/**
 * Legacy single catalog folder. Read-only compatibility: it seeds
 * catalog_roots on first load after the multi-root update and mirrors
 * roots[0] so an older build opening the same store still works.
 */
catalog_root: string | null; 
/**
 * The catalog folders. Scans and the roots UI operate on this list;
 * entries must not nest inside each other (enforced on add).
 * serde(default): a not-yet-updated frontend sends Settings without
 * this key, and its saves must not start failing.
 */
catalog_roots?: string[] | null; 
/**
 * Optional staging target: when set, Clean up builds every group's
 * canonical layout HERE, draining the raw folders into it. Unset =
 * each group cleans up inside its own folder. Must name one of
 * catalog_roots; validated at use and cleared when its folder is
 * removed.
 */
catalog_primary_root?: string | null; 
/**
 * Studios the scanner recognizes in folder names to infer a designer.
 * Seeded from scanner::DEFAULT_DESIGNERS on first load; user-editable.
 */
known_designers: string[] | null; 
/**
 * What the catalog's print button does: "open-in-slicer" (default —
 * hand the files to the OS-default slicer app) or "reveal-folder"
 * (the drag-it-yourself flow for people juggling several slicers).
 */
print_action: string | null; 
/**
 * Release-builder fields the user asked to keep across drafts (the
 * "remember" checkboxes), keyed by field id — e.g. "designer" so
 * creators don't retype their own name every release.
 */
release_field_defaults: Partial<{ [key in string]: string }> | null; 
/**
 * Zstd level for compressed-at-rest packing (None = 3, zstd's default:
 * near-Deflate speed, much better ratio). Advanced knob; -7..=22.
 */
pack_level: number | null; 
/**
 * After a packed model's files were extracted for printing/preview,
 * remove them again once the action is done (None = true).
 */
pack_cleanup_after: boolean | null; 
/**
 * The managed Blender version (e.g. "5.1.2") whose first-run setup the
 * user last completed or dismissed. A version string, not a bool, so
 * bumping the pin re-offers the dialog exactly once.
 */
blender_setup_acknowledged?: string | null; 
/**
 * The scale-reference figure ("banana for scale"): a user-supplied STL
 * rendered in grey beside the model when the studio toggle is on. Not
 * bundled with the app — the user picks any figure they like, so no
 * third-party license rides in our binary.
 */
scale_reference_path?: string | null; 
/**
 * How tall the reference stands, in the model's own mm space
 * (None = 28 — a classic tabletop human).
 */
scale_reference_height_mm?: number | null }
export type StartedStatus = { job_id: string; total_files: number; total_size_kb: number }
/**
 * A model as the release builder stages it and `model.json` records it.
 * The rich fields mirror the scanner's ModelJson reader — this is the WRITE
 * side of metadata portability (docs/3PK.md): whatever curation the catalog
 * holds rides into the sidecar, the manifest, and back out on another
 * user's scan. All optional with defaults so old sidecars still parse.
 */
export type StlModel = { id: string | null; name: string; description: string | null; tags: string[]; images: string[]; model_files: string[]; group: string | null; variant?: string | null; pose?: string | null; scale?: string | null; support_status?: string | null; release_date?: string | null; designer?: string | null; sculptor?: string | null; release_name?: string | null; 
/**
 * Base sizes in mm as canonical dimension strings: "25" for a
 * regular base, "60x35" for an oval/rectangle (never a unit suffix).
 * Both optional — plenty of models ship without a base at all.
 * Additive to model.json/3pk.
 */
base_round_mm?: string | null; base_square_mm?: string | null; 
/**
 * Per-file pose/variant assignments (a curated dump folder), restored
 * into file_variants on scan. Names are file basenames.
 */
file_poses?: FilePose[] }
export type TagCount = { tag: string; count: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
